all:
  hosts:
    ntp1.int.spans.me:
    ntp2.int.spans.me:
    aptcacher.int.spans.me:
    # dhcp.int.spans.me:
    psql1.int.spans.me:
    psql2.int.spans.me:
    wan-r1.int.spans.me:
    vpn-r1.int.spans.me:
    lab-r1.int.spans.me:
    lab-r2.int.spans.me:
    ns1.int.spans.me:
    ns2.int.spans.me:
    ghost.int.spans.me:
    factorio.int.spans.me:
  children:
    docker:
      hosts:
        dashboard.int.spans.me:
        deluge.int.spans.me:
        nginx.int.spans.me:
