all:
  children:
    lab:
      hosts:
        aptcacher.int.spans.me:
          services:
            apt-cacher-ng: apt-cacher-ng
        # dhcp.int.spans.me:
        ghost.int.spans.me:
        factorio.int.spans.me:
        # 10.0.20.206:
        git.spans.me:
        nextcloud.int.spans.me:
        docs.int.spans.me:
      children:
        docker:
          hosts:
            dashboard.int.spans.me:
              service_location: dashboard
            deluge.int.spans.me:
              service_location: deluge
            nginx.int.spans.me:
              service_location: grocy
              services:
                nginx: nginx
        nameservers:
          hosts:
            ns1.int.spans.me:
            ns2.int.spans.me:
        timeservers:
          hosts:
            ntp1.int.spans.me:
            ntp2.int.spans.me:
        databases:
          hosts:
            psql1.int.spans.me:
            psql2.int.spans.me:
        routers:
          hosts:
            wan-r1.int.spans.me:
            vpn-r1.int.spans.me:
            lab-r1.int.spans.me:
            lab-r2.int.spans.me:
    pis:
      hosts:
        rpi1.local:
        rpi2.local:
