all:
  hosts:
    aptcacher.int.spans.me:
    # dhcp.int.spans.me:
    ghost.int.spans.me:
    factorio.int.spans.me:
    # 10.0.20.207:
  children:
    docker:
      hosts:
        dashboard.int.spans.me:
        deluge.int.spans.me:
        nginx.int.spans.me:
    nameservers:
      hosts:
        ns1.int.spans.me:
        ns2.int.spans.me:
    timeservers:
      hosts:
        ntp1.int.spans.me:
        ntp2.int.spans.me:
    databases:
      hosts:
        psql1.int.spans.me:
        psql2.int.spans.me:
    routers:
      hosts:
        wan-r1.int.spans.me:
        vpn-r1.int.spans.me:
        lab-r1.int.spans.me:
        lab-r2.int.spans.me:
