all:
  children:
    lab:
      hosts:
        aptcacher.int.spans.me:
        ghost.int.spans.me:
        factorio.int.spans.me:
        nextcloud.int.spans.me:
        docs.int.spans.me:
        monitor.int.spans.me:
        nas.int.spans.me:
        mc.int.spans.me:
        deluge.int.spans.me:
        jellyfin.int.spans.me:
        gitea.int.spans.me:
      children:
        web_proxies:
          hosts:
            revprox1.int.spans.me:
              role: master
            revprox2.int.spans.me:
              role: backup
        nameservers:
          hosts:
            reso1.int.spans.me:
            reso2.int.spans.me:
            ns1.int.spans.me:
            ns2.int.spans.me:
        timeservers:
          hosts:
            ntp1.int.spans.me:
            ntp2.int.spans.me:
            ntp3.int.spans.me:
        routers:
          hosts:
            lab-r1.int.spans.me:
            lab-r2.int.spans.me:
        # kubernetes:
        #   children:
        #     kube:
        #       hosts:
        #         kube-cp-1.int.spans.me:
        #         kube-cp-2.int.spans.me:
        #         kube-cp-3.int.spans.me:
        #         kube-worker-1.int.spans.me:
        #         kube-worker-2.int.spans.me:
        #         kube-worker-3.int.spans.me:
        #         kube-worker-4.int.spans.me:
        #         kube-worker-5.int.spans.me:
        #         kube-worker-6.int.spans.me:
        #     kube_lb:
        #       hosts:
        #         kube-lb-1.int.spans.me:
        #         kube-lb-2.int.spans.me:
    lan:
      children:
        lan_dns:
          hosts:
            dns1.lan:
            dns2.lan:
      hosts:
        # rpizw1.lan:
        # rpizw2.lan:
        #  admin_user: pi
        # rpizw3.lan:
        # rpizw4.lan:
        #  admin_user: pi
        # rpizw5.lan:
        # rpizw6.lan:
        vpn.lan:
        docker.lan:
        dash.lan:
        # pkgcache.lan:
        # netboot.lan:
        backup.lan:
        mqtt.lan:
