all:
  children:
    lab:
      hosts:
        aptcacher.int.spans.me:
          services:
            apt-cacher-ng: apt-cacher-ng
        # dhcp.int.spans.me:
        ghost.int.spans.me:
        factorio.int.spans.me:
        # 10.0.20.206:
        gitlab.int.spans.me:
        nextcloud.int.spans.me:
        docs.int.spans.me:
        monitor.int.spans.me:
        nas.int.spans.me:
        minecraft.int.spans.me:
        pve1.int.spans.me:
        pve2.int.spans.me:
      children:
        docker:
          hosts:
            # dashboard.int.spans.me:
            #  service_location: dashboard
            deluge.int.spans.me:
              service_location: deluge
            nginx.int.spans.me:
              service_location: grocy
              services:
                nginx: nginx
        nameservers:
          hosts:
            ns1.int.spans.me:
            ns2.int.spans.me:
        timeservers:
          hosts:
            ntp1.int.spans.me:
            ntp2.int.spans.me:
        databases:
          hosts:
            psql1.int.spans.me:
            psql2.int.spans.me:
        routers:
          hosts:
            wan-r1.int.spans.me:
            # vpn-r1.int.spans.me:
            # lab-r1.int.spans.me:
            # lab-r2.int.spans.me:
    lan:
      hosts:
        192.168.0.2:
        192.168.0.3:
        192.168.0.11:
          admin_user: pi
        192.168.0.7:
        192.168.0.16:
        192.168.0.13:
        192.168.0.8:
          admin_user: pi
        192.168.0.14:
          admin_user: pi
        192.168.0.17:
          admin_user: pi
