---
- hosts: all
  remote_user: santeri
  become: true

  tasks:
    - name: Add Ansible user
      user:
        name: ansible
    - name: Add Ansible user to sudoers
      copy:
        dest: "/etc/sudoers.d/ansible"
        content: "ansible  ALL=(ALL)  NOPASSWD: ALL"
    - name: Deploy SSH key
      authorized_key: user=ansible
        key="{{ lookup('file', './id_ecdsa.pub') }}"
        state=present
    - name: Install Python 3 pip
      apt:
        name: python3-pip
    - name: Install Python 3 APT pip-package
      pip:
        name: python3-pip
