---
- hosts: all
  become: true

  tasks:
    - name: Install prerequirements
      apt:
        update_cache: yes
        name:
          - apt-transport-https
          - gpg
    - name: Add InfluxData apt signing key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
    - name: Add InfluxData apt package repository
      apt_repository:
        repo: deb https://repos.influxdata.com/debian buster stable
    - name: Install Telegraf
      apt:
        update_cache: yes
        name: telegraf
    - name: Copy configuration file
      copy:
        src: files/telegraf.conf
        dest: /etc/telegraf/telegraf.conf
      register: config_copied
    - name: Restart Telegraf systemd service
      systemd:
        name: telegraf
        state: restarted
      when: config_copied.changed
    - name: Enable Telegraf systemd service
      systemd:
        name: telegraf
        enabled: yes
