---
- hosts: all
  become: yes

  tasks:
    - import_tasks: update_packages.yml
      tags: packages
    - import_tasks: update_docker_services.yml
      tags: docker
      when: "'docker' in group_names"
