- name: Install prerequisites
  apt:
    name: python3-pip
    update_cache: yes
- name: Install monitoring plugins
  apt:
    name: monitoring-plugins-basic
    update_cache: yes
- name: Allow Icinga user to run certain plugins with sudo
  copy:
    dest: "/etc/sudoers.d/icinga"
    content: "icinga ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_apt\n"
    validate: "visudo -cf %s"
