- name: Install monitoring plugins
  apt:
    name: monitoring-plugins-basic
    update_cache: yes
- name: Install check_mem plugin
  get_url:
    url: https://exchange.nagios.org/components/com_mtree/attachment.php?link_id=4174&cf_id=24
    dest: /usr/lib/nagios/plugins/check_mem
    mode: 0755
