- name: Attempt to remove old monitoring user
  user:
    name: icinga
    state: absent
    remove: yes
  ignore_errors: yes
  when: inventory_hostname != 'monitor.int.spans.me'
- name: Add monitoring user
  user:
    name: monitor
    system: yes
- name: Deploy monitoring SSH key
  authorized_key:
    user: monitor
    key: "{{ lookup('file', 'id_ecdsa.pub') }}"
    state: present

- name: Set up Debian monitoring
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Set up RedHat-based monitoring
  include_tasks: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install check_mem plugin
  copy:
    src: check_mem
    dest: /usr/lib/nagios/plugins/check_mem
    mode: 0755
- name: Apply AlmaLinux patch to check_updates plugin
  patch:
    src: check_updates.patch
    dest: /usr/lib/nagios/plugins/check_updates
  when: ansible_facts['distribution'] == "AlmaLinux"
- name: Install check_systemd plugin
  pip:
    name: check_systemd
    state: latest
- name: Symlink check_systemd plugin to plugin directory
  file:
    path: /usr/lib/nagios/plugins/check_systemd
    src: /usr/local/bin/check_systemd
    state: link
