- include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- include_tasks: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Icinga user
  user:
    name: icinga
- name: Deploy Icinga SSH key
  authorized_key:
    user: icinga
    key: "{{ lookup('file', 'id_ecdsa.pub') }}"
    state: present
