- name: Set up Debian monitoring
  include_tasks: debian.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Set up RedHat-based monitoring
  include_tasks: rhel.yml
  when: ansible_facts['os_family'] == "RedHat"

- name: Install check_systemd plugin
  pip:
    name: check_systemd
    state: latest
- name: Symlink check_systemd plugin to plugin directory
  file:
    path: /usr/lib/nagios/plugins/check_systemd
    src: /usr/local/bin/check_systemd
    state: link

- name: Add Icinga user
  user:
    name: icinga
- name: Deploy Icinga SSH key
  authorized_key:
    user: icinga
    key: "{{ lookup('file', 'id_ecdsa.pub') }}"
    state: present
