- name: Install prerequisites
  dnf:
    name:
      - epel-release
      - python3-pip
    update_cache: yes
    state: latest
- name: Enable PowerTools repository
  lineinfile:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '^enabled='
    line: enabled=1
- name: Install monitoring plugins
  dnf:
    name: "nagios-plugins*"
    state: latest
- name: Create Nagios library symlink
  file:
    path: /usr/lib/nagios
    src: /usr/lib64/nagios
    state: link
- name: Install check_mem plugin
  copy:
    src: check_mem
    dest: /usr/lib64/nagios/plugins/check_mem
    mode: 0755
- name: Allow Icinga user to run certain plugins with sudo
  copy:
    dest: "/etc/sudoers.d/icinga"
    content: "icinga ALL=(ALL) NOPASSWD: /usr/lib64/nagios/plugins/check_updates\n"
    validate: visudo -cf %s

