- name: Install prerequisites
  dnf:
    name:
      - epel-release
      - python3-pip
      - patch
    update_cache: yes
    state: latest

- name: Enable PowerTools repository for CentOS
  lineinfile:
    path: /etc/yum.repos.d/CentOS-Linux-PowerTools.repo
    regexp: '^enabled='
    line: enabled=1
  when: ansible_facts['distribution'] == "CentOS"
- name: Enable PowerTools repository for AlmaLinux
  lineinfile:
    path: /etc/yum.repos.d/almalinux-powertools.repo
    regexp: '^enabled='
    line: enabled=1
  when: ansible_facts['distribution'] == "AlmaLinux"

- name: Install monitoring plugins
  dnf:
    name: "nagios-plugins*"
    state: latest
- name: Create Nagios library symlink
  file:
    path: /usr/lib/nagios
    src: /usr/lib64/nagios
    state: link
- name: Allow monitoring user to run certain plugins with sudo
  copy:
    dest: "/etc/sudoers.d/monitor"
    content: "monitor ALL=(ALL) NOPASSWD: /usr/lib64/nagios/plugins/check_updates\n"
    validate: visudo -cf %s
